### PR TITLE
Update debian 9 base image

### PR DESCRIPTION
**Pull request by joshdover**
Tests are currently failing with errors like:

```
[2023-05-09T11:29:48.765Z]     tester-debian9-64: Ign:1 http://deb.debian.org/debian stretch InRelease

[2023-05-09T11:29:48.765Z]     tester-debian9-64: Ign:2 http://security.debian.org/debian-security stretch/updates InRelease

[2023-05-09T11:29:48.765Z]     tester-debian9-64: Err:3 http://deb.debian.org/debian stretch Release

[2023-05-09T11:29:48.765Z]     tester-debian9-64:   404  Not Found [IP: 146.75.122.132 80]

[2023-05-09T11:29:48.865Z]     tester-debian9-64: Err:4 http://security.debian.org/debian-security stretch/updates Release

[2023-05-09T11:29:48.865Z]     tester-debian9-64:   404  Not Found [IP: 146.75.122.132 80]

[2023-05-09T11:29:48.865Z]     tester-debian9-64: Reading package lists...

[2023-05-09T11:29:49.567Z]     tester-debian9-64: E

[2023-05-09T11:29:49.567Z]     tester-debian9-64: : 

[2023-05-09T11:29:49.567Z]     tester-debian9-64: The repository 'http://deb.debian.org/debian stretch Release' does no longer have a Release file.

[2023-05-09T11:29:49.567Z]     tester-debian9-64: E

[2023-05-09T11:29:49.567Z]     tester-debian9-64: : 

[2023-05-09T11:29:49.567Z]     tester-debian9-64: The repository 'http://security.debian.org/debian-security stretch/updates Release' does no longer have a Release file.

```

Uses an updated Debian 9 image which _should_ have a mirror list that points to existing mirrors.

### CODE REVIEW

**Comment by joshdover** [comment]
Need to update security repo too: https://unix.stackexchange.com/questions/744401/security-repo-for-debian-stretch-not-working-anymore

**Comment by joshdover** [comment]
I can't get vagrant to bring this machine up locally, I suspect because I'm using an M1 machine. Will find someone else with an Intel machine to fix this up.

**Comment by michalpristas** [comment]
do note merge i'm testing this

**Comment by joshdover** [comment]
This is now failing because the tests are trying to fetch snapshot versions that no longer exist. Will fix that in separate PR

**Pull request merged**
