### PR TITLE
Update ansible to latest supported version

### PR DESCRIPTION
**Pull request by mikemadden42**

### CODE REVIEW

**Comment by mikemadden42** [comment]
Jumping from `2.4.5` to `2.7.10' introduces some deprecation warnings.  I would vote we address the security issue in this PR and then open a new PR to address the deprecations.

```
DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|version_compare` use `result is version_compare`. This feature will be removed in
version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

There are many warnings related to filters.

```bash
$ egrep -i 'deprecation warning' tester-debian8-64.log | egrep -c 'filters'
614
```

**Comment by mikemadden42** [comment]
I plan on testing the following vagrant boxes with ansible `2.7.10`.  I'll test them a box at and time locally and update this checklist.

- [ ] tester-debian8-64
- [ ] tester-debian9-64
- [ ] tester-ubuntu1204-32
- [ ] tester-ubuntu1404-64
- [ ] tester-ubuntu1604-64
- [ ] tester-ubuntu1804-64
- [ ] tester-awslinux
- [ ] tester-awslinux2
- [ ] tester-centos6-32
- [ ] tester-centos6-64
- [ ] tester-centos7-64
- [ ] tester-opensuse42-64
- [ ] tester-sles12-64
- [ ] tester-win12-64

**Comment by mikemadden42** [comment]
Ran into an error on Windows 2012.

```
fatal: [tester-win12-64]: FAILED! => {"changed": false, "msg": "Invalid options for assert: not"}
	to retry, use: --limit @/Users/madden/src/mikemadden42/beats-tester/elastic.retry

PLAY RECAP **************************************************************************************************************************************************************
tester-win12-64            : ok=41   changed=16   unreachable=0    failed=1```

**Comment by mikemadden42** [comment]
Windows 2012 tests are stalling in this step:

```
TASK [common : Download package sha512 (windows)] ***********************************************************************************************************************
task path: /Users/madden/src/mikemadden42/beats-tester/roles/common/tasks/download.yml:6
Using module file /Users/madden/src/mikemadden42/beats-tester/ve/lib/python2.7/site-packages/ansible/modules/windows/win_get_url.ps1
<localhost> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5985 TO localhost
checking if winrm_host localhost is an IPv6 address
```

**Comment by andrewkroh** [comment]
So it's hung up while connecting to the Windows host after upgrading Ansible versions? Or is hung while downloading?

If it's something to do with the connection maybe try the latest pywinrm package.

**Comment by mikemadden42** [comment]
I'm retesting with ansible `2.8.1`.  I'll test them a box at and time locally and update this checklist.

- [] tester-debian8-64
- [] tester-debian9-64
- [] tester-ubuntu1204-32
- [] tester-ubuntu1404-64
- [] tester-ubuntu1604-64
- [] tester-ubuntu1804-64
- [] tester-awslinux
- [] tester-awslinux2
- [] tester-centos6-32
- [] tester-centos6-64
- [] tester-centos7-64
- [] tester-opensuse42-64
- [] tester-sles12-64
- [ ] tester-win12-64

**Pull request merged**
