### PR TITLE
Add packaging tests for Heartbeat

### PR DESCRIPTION
**Pull request by tsg**
Smoke tests using a simple HTTP monitor.

### CODE REVIEW

**Comment by andrewkroh** [comment]
I'm looking into why Jenkins didn't post a status on this PR. http://build-eu-00.elastic.co/view/Beats/job/beats-tester-PR/

**Comment by andrewkroh** [comment]
jenkins, test it

**Comment by andrewkroh** [comment]
jenkins, test it

**Comment by andrewkroh** [comment]
jenkins, test it

**Comment by tsg** [comment]
@andrewkroh Thanks for getting the Jenkins build!

**Comment by tsg** [comment]
Tests are currently failing due to: https://github.com/elastic/beats/issues/3273

**Comment by andrewkroh** [comment]
jenkins, test it

**Pull request merged**
